### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'LOCALPATH\chat-app\backend\routes\public\index.html' at Error (native)

### ISSUE THREAD

**Issue by joedaouddotcom** [cats-with-potatos/chat-app#13]
Error: ENOENT: no such file or directory, stat 'LOCALPATH\chat-app\backend\routes\public\index.html' at Error (native)
Error occurs when refreshing the page on any route /login /signup /sample2

**Comment by joedaouddotcom** [comment]
This was determined to be an issue with the backend in angularRoutes.js. Assigned to backend guys but I will also look into this

**Comment by RafGDev** [comment]
This has been changed.
