### ISSUE TITLE
Login Validation on Node Routes

### ISSUE THREAD

**Issue by jp-webdev** [cats-with-potatos/chat-app#6]
Users who are logging in should have to follow a set of basic username and password standards. (Use of lowercase and capital letters on usernames, mixed characters and numbers on passwords, etc). Some steps have to be taken to ensure that users are not able to re-use usernames.

Using regex should make validating usernames and passwords (for content) simple. A few SQL queries should take care of the re-using usernames issue. 

I'll have to learn more about how Node uses SQL and regex, and then I can implement the search pattern, and those queries.

**Comment by RafGDev** [comment]
This has been implemented in #7 and merged into the dev branch.
