### ISSUE TITLE
Header Menu Shadow Not Changing

### ISSUE THREAD

**Issue by jp-webdev** [cats-with-potatos/chat-app#8]
Hey guys,

So I was running some tests on the Dev branch, and I noticed that if you click the Sign Up menu option, the Login menu option stays selected, even when the page switches.

You can see the issue below:
![login-signup-shadow-bug](https://cloud.githubusercontent.com/assets/21113040/17872495/4fa4da84-688e-11e6-918e-581c8ac6ae3f.PNG)

**Comment by JGefroh** [comment]
The library we're using to handle routing, `ui-router`, provides a directive, `ui-sref-active`, to indicate a style that should be applied to an element if the current state/route matches the link's `ui-sref`. You can use this to toggle different styles in the navigation links depending on the current page.
